// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import AIHistoricalContextAgentConcept from "./AIHistoricalContextAgent/AIHistoricalContextAgentConcept.ts";
import LocationChatLedgerConcept from "./LocationChatLedger/LocationChatLedgerConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import UserAuthenticationConcept from "./UserAuthentication/UserAuthenticationConcept.ts";

export type { default as AIHistoricalContextAgentConcept } from "./AIHistoricalContextAgent/AIHistoricalContextAgentConcept.ts";
export type { default as LocationChatLedgerConcept } from "./LocationChatLedger/LocationChatLedgerConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as UserAuthenticationConcept } from "./UserAuthentication/UserAuthenticationConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

export const AIHistoricalContextAgent = Engine.instrumentConcept(new AIHistoricalContextAgentConcept(db));
export const LocationChatLedger = Engine.instrumentConcept(new LocationChatLedgerConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const UserAuthentication = Engine.instrumentConcept(new UserAuthenticationConcept(db));
