// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually.


import type { Sync } from "@engine";

import * as sync_authenticated from "./authenticated.sync.ts";

const allSyncs: Record<string, Sync> = {};


for (const [name, func] of Object.entries(sync_authenticated)) {
  if (typeof func === "function") {
    allSyncs[`authenticated.${name}`] = func as Sync;
  }
}

export default allSyncs;
